---
- name: Configuring apache2
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ default_apache2_confs }}"

# Custom client config 

- name: Create custom directory
  file:
    path: " {{ custom_config_path }} "
    state: directory
    mode: "u=rwx,g=rx,o=rx"


- name: Confirm custom directory is added
  shell: ls -alh {{ custom_config_path }}
  changed_when: false
  register: echo_custom_directory                                                                                                                                 

- name: show echo_custom_directory
  debug: msg="{{ echo_custom_directory.stdout }}"


- name: add custom config
  template:
    src: "{{ item }}.j2"
    dest: "{{ custom_config_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ custom_conf }}"
