---
- name: Disable mpm_worker and ignore warnings about missing mpm module
  community.general.apache2_module:
    state: absent
    name: mpm_event
    ignore_configcheck: True

- name: Enabling MPM modules
  command: >
    a2enmod {{ item.id }}
  args:
    creates: "/etc/apache2/mods-enabled/{{ item.id }}.load"
  when: item.state is not defined or item.state != 'absent'
  with_items: "{{ mpm_modules }}"

- name: Disabling MPM modules
  command: >
    a2dismod {{ item.id }}
  args:
    removes: "/etc/apache2/mods-enabled/{{ item.id }}.load"
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ mpm_modules }}"
