---

- name: Enabling MPM modules
  command: >
    a2enmod {{ item.id }}
  args:
    creates: "/etc/apache2/mods-enabled/{{ item.id }}.load"
  when: item.state is not defined or item.state != 'absent'
  with_items: "{{ mpm_modules }}"

- name: Disabling MPM modules
  command: >
    a2dismod {{ item.id }}
  args:
    removes: "/etc/apache2/mods-enabled/{{ item.id }}.load"
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ mpm_modules }}"
