---
- name: show enabled modules
  command: >
    apache2ctl -M
  when: mpm_prefork_is_enabled
  register: echo_enabled_module
  ignore_errors: yes

- name: show enabled module
  debug: msg="{{ echo_enabled_module.stdout }}"
  ignore_errors: yes

- name: restart apache2
  service: name=apache2 state=restarted
  when: mpm_prefork_is_enabled
  ignore_errors: yes

- name: show2 enabled modules
  command: >
    apache2ctl -M
  when: mpm_prefork_is_enabled
  register: echo2_enabled_module
  ignore_errors: yes

- name: show2 enabled module
  debug: msg="{{ echo2_enabled_module.stdout }}"
  ignore_errors: yes

- name: Disabling mpm_event modules
  apache2_module:
    state: absent
    name: mpm_event
    ignore_configcheck: True
    force: True
  when: mpm_prefork_is_enabled
  ignore_errors: yes

- name: reload apache2
  service: name=apache2 state=restarted
  when: mpm_prefork_is_enabled
  ignore_errors: yes

- name: show3 enabled modules
  command: >
    apache2ctl -M
  when: mpm_prefork_is_enabled
  register: echo3_enabled_module

- name: show3 enabled module
  debug: msg="{{ echo3_enabled_module.stdout }}"

- name: Enabling mpm_prefork modules
  apache2_module:
    state: present
    name: mpm_prefork
    ignore_configcheck: True
    force: True
  when: mpm_prefork_is_enabled



#- apache2_module:
#    state: absent
#    name: autoindex
#    force: True
