---

- name: Enabling modules
  apache2_module:
    state: present
    name: "{{ item.id }}"
    ignore_configcheck: True
  with_items: "{{ apache2_modules }}"

- name: Disabling modules
  apache2_module:
    state: absent
    name: "{{ item.id }}"
    ignore_configcheck: True
  with_items: "{{ apache2_modules }}"
