---
- name: Force disabling default mpm_event module
  apache2_module:
    state: absent
    name: mpm_event
    ignore_configcheck: True
    force: True
  when: mpm_prefork_is_enabled

- name: Enabling mpm_prefork modules
  apache2_module:
    state: present
    name: mpm_prefork
    ignore_configcheck: True
  when: mpm_prefork_is_enabled

- name: restart apache2
  service: name=apache2 state=restarted
  when: mpm_prefork_is_enabled
