---
- name: Disable mpm_worker and ignore warnings about missing mpm module
  apache2_module:
    state: absent
    name: mpm_event
    ignore_configcheck: True

- name: Disable mpm_prefork and ignore warnings about missing mpm module
  apache2_module:
    state: present
    name: mpm_prefork
    ignore_configcheck: True
